# Generated by Django 5.1.5 on 2025-03-02 14:32

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullshop', '0003_product_count_product_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('active_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=2000),
        ),
    ]
