# Generated by Django 5.1.5 on 2025-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullshop', '0004_alter_product_managers_alter_product_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(choices=[(0, 'Товар в продаже'), (1, 'Товар не в продаже')], default=1),
        ),
    ]
