# Generated by Django 5.1.5 on 2025-03-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullshop', '0005_alter_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fullshop.category'),
        ),
    ]
